### ISSUE TITLE
Bug: Failed opened required

### ISSUE THREAD

**Issue by akuchalskij** [beGateway/bitrix-payment-module#7]
При подключении данного модуля, заметил, что:
в include.php для автозагрузки классов  Вы указываете: 
`  "\BeGateway\QueryByToken" => "$lib_path/QueryByToken.php",`
 в файле begateway.payment/install/components/begateway/transaction.info/class.php 
пытаетесь подтянуть QueryByToken, но в lib/ такого класса нет, есть только QueryByPaymentToken

**Comment by avsh** [comment]
Обновили модуль до 4.0.0 версии, перешли на оплату в виджете и отказались от компонента
